language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: cswCyiva3X7XhRzB73q6fUwujIKCzfWLUfqTwZ7aSpvRro0BPktEcMNeOjj0fvq2TJBI0d4yLmlSGIWn/n1X6VPvbCUVfTtMtnNEgBbm82t/K7ILhAyjUFbuLBTZBsKr2r6YV8lCyKXY5cFBb6xR+xa5xRCqvzsAlUGM9gh5Q85seWHGXs10bHaH7b1EuF+kKTO9ohLTz/h6cbOOdnPiqEHssc7+o96WE7tb876OWUYkUzmjy2WWtLoNKcsZlj7b7zP2vuw6GdmgkijWpxzf42dovEG5tOH2qTSDrIM7sLqOZZmFtWV+aBmn0yhbxkm9QeVWwb8Hjam0DLBFL3IGD1gZY3adtuqFK2l040Bc6PiMCWYjr4g2XHsDWjv4X+6jGXM6YP0mbySPwuwZ0z3pJx3IEy2N24pg4VduEBkYvy6zVH+4Z3BIx8E6VBLrPSACg4mzUdqWJ1vOzfsxxGOzPpuEWk0eK0i0ENWpKqa0RzngXs1kxAEg3sX57BB9Wz5t09sA5app3S7iHrRACjArIwB2WidyVeYYo9hF3WOxOOcOyj2MZTEAsh2hcoHHFI5IZxqJHmGSGk7dYJDLkBI/ROlt8kbA9mQmcO+pILiMCjYYI5s+dOvPg4ubEsv19828iTuhUtJ975mrVhp53xBFSEqVpWnWWYlQST9eUIuWz6c=
  app: ajcrcarent
  on:
    repo: RafaelAndrade1999/carent
